// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package aimtp_controller

import (
	"aimtp/internal/aimtp_controller/biz"
	"aimtp/internal/aimtp_controller/pkg/validation"
	"aimtp/internal/aimtp_controller/store"
	"aimtp/internal/pkg/server"
)

// Injectors from wire.go:

func InitializeServer(config *Config) (server.Server, error) {
	string2 := config.ServerMode
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(db)
	restConfig, err := ProvideK8sRESTConfig(config)
	if err != nil {
		return nil, err
	}
	clientset, err := ProvideKubeClient(restConfig)
	if err != nil {
		return nil, err
	}
	versionedClientset, err := ProvideVolcanoClient(restConfig)
	if err != nil {
		return nil, err
	}
	clientset2, err := ProvideArgoClient(restConfig)
	if err != nil {
		return nil, err
	}
	configOptions := config.K8sOptions
	bizBiz := biz.NewBiz(datastore, clientset, versionedClientset, clientset2, configOptions)
	validator := validation.New(datastore)
	serverConfig := &ServerConfig{
		cfg:           config,
		biz:           bizBiz,
		val:           validator,
		restConfig:    restConfig,
		kubeClient:    clientset,
		volcanoClient: versionedClientset,
		argoClient:    clientset2,
	}
	serverServer, err := NewWebServer(string2, serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
