// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package aimtp_controller

import (
	"aimtp/internal/aimtp_controller/biz"
	"aimtp/internal/aimtp_controller/pkg/validation"
	"aimtp/internal/aimtp_controller/store"
	"aimtp/internal/pkg/server"
)

// Injectors from wire.go:

func InitializeServer(config *Config) (server.Server, error) {
	string2 := config.ServerMode
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(db)
	bizBiz := biz.NewBiz(datastore)
	validator := validation.New(datastore)
	serverConfig := &ServerConfig{
		cfg: config,
		biz: bizBiz,
		val: validator,
	}
	serverServer, err := NewWebServer(string2, serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
