// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package aimtp_server

import (
	"aimtp/internal/aimtp_server/biz"
	"aimtp/internal/aimtp_server/pkg/validation"
	"aimtp/internal/aimtp_server/store"
	"aimtp/internal/pkg/client"
	"aimtp/internal/pkg/server"
)

// Injectors from wire.go:

func InitializeServer(config *Config) (server.Server, error) {
	string2 := config.ServerMode
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(db)
	v := config.ControllerClusters
	v2, err := client.NewControllerClients(v)
	if err != nil {
		return nil, err
	}
	bizBiz := biz.NewBiz(datastore, v2)
	validator := validation.New(datastore)
	serverConfig := &ServerConfig{
		cfg: config,
		biz: bizBiz,
		val: validator,
	}
	serverServer, err := NewWebServer(string2, serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
