// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package aimtp_server

import (
	"aimtp/internal/pkg/server"
)

// Injectors from wire.go:

func InitializeServer(config *Config) (server.Server, error) {
	string2 := config.ServerMode
	serverConfig := &ServerConfig{
		cfg: config,
	}
	serverServer, err := NewWebServer(string2, serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
