// Copyright 2024 许铭杰 (1044011439@qq.com). All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// AIMTP API 定义，包含健康检查、用户管理和文章管理的 RPC 接口

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.1
// source: aimtp_server/v1/aimtp_server.proto

package aimtp_server_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_aimtp_server_v1_aimtp_server_proto protoreflect.FileDescriptor

const file_aimtp_server_v1_aimtp_server_proto_rawDesc = "" +
	"\n" +
	"\"aimtp_server/v1/aimtp_server.proto\x12\x0faimtp_server_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1daimtp_server/v1/healthz.proto2e\n" +
	"\fAIMTP_SERVER\x12U\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a .aimtp_server_v1.HealthzResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthzB/Z-aimtp/pkg/api/aimtp_server/v1;aimtp_server_v1b\x06proto3"

var file_aimtp_server_v1_aimtp_server_proto_goTypes = []any{
	(*emptypb.Empty)(nil),   // 0: google.protobuf.Empty
	(*HealthzResponse)(nil), // 1: aimtp_server_v1.HealthzResponse
}
var file_aimtp_server_v1_aimtp_server_proto_depIdxs = []int32{
	0, // 0: aimtp_server_v1.AIMTP_SERVER.Healthz:input_type -> google.protobuf.Empty
	1, // 1: aimtp_server_v1.AIMTP_SERVER.Healthz:output_type -> aimtp_server_v1.HealthzResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aimtp_server_v1_aimtp_server_proto_init() }
func file_aimtp_server_v1_aimtp_server_proto_init() {
	if File_aimtp_server_v1_aimtp_server_proto != nil {
		return
	}
	file_aimtp_server_v1_healthz_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aimtp_server_v1_aimtp_server_proto_rawDesc), len(file_aimtp_server_v1_aimtp_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aimtp_server_v1_aimtp_server_proto_goTypes,
		DependencyIndexes: file_aimtp_server_v1_aimtp_server_proto_depIdxs,
	}.Build()
	File_aimtp_server_v1_aimtp_server_proto = out.File
	file_aimtp_server_v1_aimtp_server_proto_goTypes = nil
	file_aimtp_server_v1_aimtp_server_proto_depIdxs = nil
}
