// Healthz API 定义，包含健康检查响应的相关消息和状态

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.1
// source: aimtp_server/v1/dag.proto

package aimtp_server_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDAGRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ========== 内部字段（由中间件注入）==========
	// @gotags: json:"-"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"-"` // 内部ID
	// @gotags: binding:"-"
	Uid int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty" binding:"-"` // 用户ID
	// @gotags: binding:"-"
	Uname string `protobuf:"bytes,3,opt,name=uname,proto3" json:"uname,omitempty" binding:"-"` // 用户名
	// @gotags: binding:"-"
	OuName string `protobuf:"bytes,4,opt,name=ou_name,json=ouName,proto3" json:"ou_name,omitempty" binding:"-"` // 组织单元名称
	// @gotags: binding:"-"
	OuId       int64  `protobuf:"varint,5,opt,name=ou_id,json=ouId,proto3" json:"ou_id,omitempty" binding:"-"`                  // 组织单元ID
	DeviceType string `protobuf:"bytes,6,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // 设备类型
	// ========== 鉴权信息 ==========
	AppId         string `protobuf:"bytes,7,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppKey        string `protobuf:"bytes,8,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDAGRequest) Reset() {
	*x = CreateDAGRequest{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDAGRequest) ProtoMessage() {}

func (x *CreateDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDAGRequest.ProtoReflect.Descriptor instead.
func (*CreateDAGRequest) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDAGRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateDAGRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateDAGRequest) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *CreateDAGRequest) GetOuName() string {
	if x != nil {
		return x.OuName
	}
	return ""
}

func (x *CreateDAGRequest) GetOuId() int64 {
	if x != nil {
		return x.OuId
	}
	return 0
}

func (x *CreateDAGRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *CreateDAGRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateDAGRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{1}
}

type AsyncTasks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncTasks) Reset() {
	*x = AsyncTasks{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncTasks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncTasks) ProtoMessage() {}

func (x *AsyncTasks) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncTasks.ProtoReflect.Descriptor instead.
func (*AsyncTasks) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{2}
}

type CreateDAGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDAGResponse) Reset() {
	*x = CreateDAGResponse{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDAGResponse) ProtoMessage() {}

func (x *CreateDAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDAGResponse.ProtoReflect.Descriptor instead.
func (*CreateDAGResponse) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{3}
}

var File_aimtp_server_v1_dag_proto protoreflect.FileDescriptor

const file_aimtp_server_v1_dag_proto_rawDesc = "" +
	"\n" +
	"\x19aimtp_server/v1/dag.proto\x12\x0faimtp_server_v1\"\xc9\x01\n" +
	"\x10CreateDAGRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05uname\x18\x03 \x01(\tR\x05uname\x12\x17\n" +
	"\aou_name\x18\x04 \x01(\tR\x06ouName\x12\x13\n" +
	"\x05ou_id\x18\x05 \x01(\x03R\x04ouId\x12\x1f\n" +
	"\vdevice_type\x18\x06 \x01(\tR\n" +
	"deviceType\x12\x15\n" +
	"\x06app_id\x18\a \x01(\tR\x05appId\x12\x17\n" +
	"\aapp_key\x18\b \x01(\tR\x06appKey\"\x06\n" +
	"\x04Task\"\f\n" +
	"\n" +
	"AsyncTasks\"\x13\n" +
	"\x11CreateDAGResponseB/Z-aimtp/pkg/api/aimtp_server/v1;aimtp_server_v1b\x06proto3"

var (
	file_aimtp_server_v1_dag_proto_rawDescOnce sync.Once
	file_aimtp_server_v1_dag_proto_rawDescData []byte
)

func file_aimtp_server_v1_dag_proto_rawDescGZIP() []byte {
	file_aimtp_server_v1_dag_proto_rawDescOnce.Do(func() {
		file_aimtp_server_v1_dag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aimtp_server_v1_dag_proto_rawDesc), len(file_aimtp_server_v1_dag_proto_rawDesc)))
	})
	return file_aimtp_server_v1_dag_proto_rawDescData
}

var file_aimtp_server_v1_dag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aimtp_server_v1_dag_proto_goTypes = []any{
	(*CreateDAGRequest)(nil),  // 0: aimtp_server_v1.CreateDAGRequest
	(*Task)(nil),              // 1: aimtp_server_v1.Task
	(*AsyncTasks)(nil),        // 2: aimtp_server_v1.AsyncTasks
	(*CreateDAGResponse)(nil), // 3: aimtp_server_v1.CreateDAGResponse
}
var file_aimtp_server_v1_dag_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aimtp_server_v1_dag_proto_init() }
func file_aimtp_server_v1_dag_proto_init() {
	if File_aimtp_server_v1_dag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aimtp_server_v1_dag_proto_rawDesc), len(file_aimtp_server_v1_dag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aimtp_server_v1_dag_proto_goTypes,
		DependencyIndexes: file_aimtp_server_v1_dag_proto_depIdxs,
		MessageInfos:      file_aimtp_server_v1_dag_proto_msgTypes,
	}.Build()
	File_aimtp_server_v1_dag_proto = out.File
	file_aimtp_server_v1_dag_proto_goTypes = nil
	file_aimtp_server_v1_dag_proto_depIdxs = nil
}
