// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDagStatusSummaryM = "dag_status_summary"

// DagStatusSummaryM DAG状态摘要表
type DagStatusSummaryM struct {
	DagID           int64          `gorm:"column:dag_id;primaryKey;autoIncrement:true;comment:DAG自增ID" json:"dag_id"`                                            // DAG自增ID
	DagName         string         `gorm:"column:dag_name;not null;comment:DAG名称(唯一)" json:"dag_name"`                                                           // DAG名称(唯一)
	Cluster         string         `gorm:"column:cluster;not null;comment:所属集群" json:"cluster"`                                                                  // 所属集群
	UserName        string         `gorm:"column:user_name;not null;comment:DAG所属用户" json:"user_name"`                                                           // DAG所属用户
	QueueName       *string        `gorm:"column:queue_name;comment:DAG所属队列" json:"queue_name"`                                                                  // DAG所属队列
	Engine          *string        `gorm:"column:engine;default:volcano;comment:执行引擎: volcano/argo" json:"engine"`                                               // 执行引擎: volcano/argo
	State           string         `gorm:"column:state;not null;default:pending;comment:DAG状态: pending/creating/running/succeeded/failed" json:"state"`          // DAG状态: pending/creating/running/succeeded/failed
	CreationStatus  string         `gorm:"column:creation_status;not null;default:pending;comment:创建状态: pending/creating/created/failed" json:"creation_status"` // 创建状态: pending/creating/created/failed
	Payload         *string        `gorm:"column:payload;comment:DAG定义JSON (创建后可清空)" json:"payload"`                                                             // DAG定义JSON (创建后可清空)
	ErrorMsg        *string        `gorm:"column:error_msg;comment:创建失败原因" json:"error_msg"`                                                                     // 创建失败原因
	RetryCount      *int32         `gorm:"column:retry_count;comment:重新创建次数" json:"retry_count"`                                                                 // 重新创建次数
	MaxRetries      *int32         `gorm:"column:max_retries;default:3;comment:最大重新创建次数" json:"max_retries"`                                                     // 最大重新创建次数
	TotalJobs       *int32         `gorm:"column:total_jobs;comment:总Job数量" json:"total_jobs"`                                                                   // 总Job数量
	CompletedJobs   *int32         `gorm:"column:completed_jobs;comment:已完成Job数量" json:"completed_jobs"`                                                         // 已完成Job数量
	FailedJobs      *int32         `gorm:"column:failed_jobs;comment:失败Job数量" json:"failed_jobs"`                                                                // 失败Job数量
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                  // 创建时间
	StartedAt       *time.Time     `gorm:"column:started_at;comment:DAG开始运行时间" json:"started_at"`                                                                // DAG开始运行时间
	FinishedAt      *time.Time     `gorm:"column:finished_at;comment:DAG结束时间" json:"finished_at"`                                                                // DAG结束时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                  // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                                                     // 删除时间
	ResourceVersion *string        `gorm:"column:resource_version;comment:Kubernetes ResourceVersion" json:"resource_version"`                                   // Kubernetes ResourceVersion
	Version         *int64         `gorm:"column:version;comment:版本号（纳秒时间戳）" json:"version"`                                                                     // 版本号（纳秒时间戳）
}

// TableName DagStatusSummaryM's table name
func (*DagStatusSummaryM) TableName() string {
	return TableNameDagStatusSummaryM
}
