// Copyright 2024 许铭杰 (1044011439@qq.com). All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// AIMTP API 定义，包含健康检查、用户管理和文章管理的 RPC 接口

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.1
// source: aimtp_controller/v1/aimtp_controller.proto

package aimtp_controller_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIMTP_CONTROLLER_Healthz_FullMethodName   = "/aimtp_controller_v1.AIMTP_CONTROLLER/Healthz"
	AIMTP_CONTROLLER_CreateDAG_FullMethodName = "/aimtp_controller_v1.AIMTP_CONTROLLER/CreateDAG"
)

// AIMTP_CONTROLLERClient is the client API for AIMTP_CONTROLLER service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIMTP_CONTROLLERClient interface {
	// Healthz 健康检查
	Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
	CreateDAG(ctx context.Context, in *CreateDAGRequest, opts ...grpc.CallOption) (*CreateDAGResponse, error)
}

type aIMTP_CONTROLLERClient struct {
	cc grpc.ClientConnInterface
}

func NewAIMTP_CONTROLLERClient(cc grpc.ClientConnInterface) AIMTP_CONTROLLERClient {
	return &aIMTP_CONTROLLERClient{cc}
}

func (c *aIMTP_CONTROLLERClient) Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, AIMTP_CONTROLLER_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIMTP_CONTROLLERClient) CreateDAG(ctx context.Context, in *CreateDAGRequest, opts ...grpc.CallOption) (*CreateDAGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDAGResponse)
	err := c.cc.Invoke(ctx, AIMTP_CONTROLLER_CreateDAG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIMTP_CONTROLLERServer is the server API for AIMTP_CONTROLLER service.
// All implementations must embed UnimplementedAIMTP_CONTROLLERServer
// for forward compatibility.
type AIMTP_CONTROLLERServer interface {
	// Healthz 健康检查
	Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error)
	CreateDAG(context.Context, *CreateDAGRequest) (*CreateDAGResponse, error)
	mustEmbedUnimplementedAIMTP_CONTROLLERServer()
}

// UnimplementedAIMTP_CONTROLLERServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIMTP_CONTROLLERServer struct{}

func (UnimplementedAIMTP_CONTROLLERServer) Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedAIMTP_CONTROLLERServer) CreateDAG(context.Context, *CreateDAGRequest) (*CreateDAGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDAG not implemented")
}
func (UnimplementedAIMTP_CONTROLLERServer) mustEmbedUnimplementedAIMTP_CONTROLLERServer() {}
func (UnimplementedAIMTP_CONTROLLERServer) testEmbeddedByValue()                          {}

// UnsafeAIMTP_CONTROLLERServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIMTP_CONTROLLERServer will
// result in compilation errors.
type UnsafeAIMTP_CONTROLLERServer interface {
	mustEmbedUnimplementedAIMTP_CONTROLLERServer()
}

func RegisterAIMTP_CONTROLLERServer(s grpc.ServiceRegistrar, srv AIMTP_CONTROLLERServer) {
	// If the following call pancis, it indicates UnimplementedAIMTP_CONTROLLERServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIMTP_CONTROLLER_ServiceDesc, srv)
}

func _AIMTP_CONTROLLER_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIMTP_CONTROLLERServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIMTP_CONTROLLER_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIMTP_CONTROLLERServer).Healthz(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIMTP_CONTROLLER_CreateDAG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIMTP_CONTROLLERServer).CreateDAG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIMTP_CONTROLLER_CreateDAG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIMTP_CONTROLLERServer).CreateDAG(ctx, req.(*CreateDAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIMTP_CONTROLLER_ServiceDesc is the grpc.ServiceDesc for AIMTP_CONTROLLER service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIMTP_CONTROLLER_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aimtp_controller_v1.AIMTP_CONTROLLER",
	HandlerType: (*AIMTP_CONTROLLERServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _AIMTP_CONTROLLER_Healthz_Handler,
		},
		{
			MethodName: "CreateDAG",
			Handler:    _AIMTP_CONTROLLER_CreateDAG_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aimtp_controller/v1/aimtp_controller.proto",
}
