// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJobStatusM = "job_status"

// JobStatusM Job状态表
type JobStatusM struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                                                        // 自增ID
	JobID             string         `gorm:"column:job_id;not null;comment:Job全局唯一ID" json:"job_id"`                                                                // Job全局唯一ID
	DagID             int64          `gorm:"column:dag_id;not null;comment:DAG ID（关联 dag_status.dag_id）" json:"dag_id"`                                             // DAG ID（关联 dag_status.dag_id）
	DagName           string         `gorm:"column:dag_name;not null;comment:DAG名称" json:"dag_name"`                                                                // DAG名称
	JobName           string         `gorm:"column:job_name;not null;comment:Job名称（任务名）" json:"job_name"`                                                           // Job名称（任务名）
	Cluster           string         `gorm:"column:cluster;not null;comment:集群名称" json:"cluster"`                                                                   // 集群名称
	JobType           string         `gorm:"column:job_type;not null;default:volcano_job;comment:Job类型：volcano_job" json:"job_type"`                                // Job类型：volcano_job
	Engine            string         `gorm:"column:engine;not null;default:volcano;comment:执行引擎：volcano" json:"engine"`                                             // 执行引擎：volcano
	VjName            *string        `gorm:"column:vj_name;comment:Volcano Job 名称" json:"vj_name"`                                                                  // Volcano Job 名称
	WorkflowName      *string        `gorm:"column:workflow_name;comment:Argo Workflow 名称（多Job DAG）" json:"workflow_name"`                                          // Argo Workflow 名称（多Job DAG）
	NodeID            *string        `gorm:"column:node_id;comment:Argo Node ID" json:"node_id"`                                                                    // Argo Node ID
	Namespace         *string        `gorm:"column:namespace;default:default;comment:命名空间" json:"namespace"`                                                        // 命名空间
	State             string         `gorm:"column:state;not null;default:pending;comment:Job状态：pending/queuing/running/succeeded/failed/terminating" json:"state"` // Job状态：pending/queuing/running/succeeded/failed/terminating
	Message           *string        `gorm:"column:message;comment:详细消息" json:"message"`                                                                            // 详细消息
	Reason            *string        `gorm:"column:reason;comment:原因" json:"reason"`                                                                                // 原因
	ExpectedPodCount  *int32         `gorm:"column:expected_pod_count;default:1;comment:期望Pod数量" json:"expected_pod_count"`                                         // 期望Pod数量
	RunningPodCount   *int32         `gorm:"column:running_pod_count;comment:运行中Pod数量" json:"running_pod_count"`                                                    // 运行中Pod数量
	SucceededPodCount *int32         `gorm:"column:succeeded_pod_count;comment:成功Pod数量" json:"succeeded_pod_count"`                                                 // 成功Pod数量
	FailedPodCount    *int32         `gorm:"column:failed_pod_count;comment:失败Pod数量" json:"failed_pod_count"`                                                       // 失败Pod数量
	RetryCount        *int32         `gorm:"column:retry_count;comment:重试次数" json:"retry_count"`                                                                    // 重试次数
	Priority          *int32         `gorm:"column:priority;comment:优先级" json:"priority"`                                                                           // 优先级
	CreatedAt         *time.Time     `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                                      // 创建时间
	StartedAt         *time.Time     `gorm:"column:started_at;comment:开始时间" json:"started_at"`                                                                      // 开始时间
	FinishedAt        *time.Time     `gorm:"column:finished_at;comment:结束时间" json:"finished_at"`                                                                    // 结束时间
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                   // 更新时间
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                                                      // 删除时间
	JobHome           *string        `gorm:"column:job_home;comment:Job归档路径" json:"job_home"`                                                                       // Job归档路径
	Duration          *int32         `gorm:"column:duration;comment:运行时长（秒）" json:"duration"`                                                                       // 运行时长（秒）
	ExtraInfo         *string        `gorm:"column:extra_info;comment:额外信息" json:"extra_info"`                                                                      // 额外信息
}

// TableName JobStatusM's table name
func (*JobStatusM) TableName() string {
	return TableNameJobStatusM
}
