// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePodStatusM = "pod_status"

// PodStatusM Pod状态表
type PodStatusM struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                                    // 自增ID
	PodName       string         `gorm:"column:pod_name;not null;comment:Pod名称" json:"pod_name"`                                            // Pod名称
	JobID         string         `gorm:"column:job_id;not null;comment:所属Job ID" json:"job_id"`                                             // 所属Job ID
	DagName       string         `gorm:"column:dag_name;not null;comment:DAG名称" json:"dag_name"`                                            // DAG名称
	Cluster       string         `gorm:"column:cluster;not null;comment:集群名称" json:"cluster"`                                               // 集群名称
	UUID          *string        `gorm:"column:uuid;comment:Job UUID（用于关联重试）" json:"uuid"`                                                  // Job UUID（用于关联重试）
	ReplicaIndex  *int32         `gorm:"column:replica_index;comment:副本索引（分布式训练）" json:"replica_index"`                                     // 副本索引（分布式训练）
	RetryIndex    *int32         `gorm:"column:retry_index;comment:重试索引" json:"retry_index"`                                                // 重试索引
	Namespace     *string        `gorm:"column:namespace;default:default;comment:命名空间" json:"namespace"`                                    // 命名空间
	NodeName      *string        `gorm:"column:node_name;comment:节点名称" json:"node_name"`                                                    // 节点名称
	PodIP         *string        `gorm:"column:pod_ip;comment:Pod IP" json:"pod_ip"`                                                        // Pod IP
	HostIP        *string        `gorm:"column:host_ip;comment:主机IP" json:"host_ip"`                                                        // 主机IP
	State         string         `gorm:"column:state;not null;default:pending;comment:Pod状态：pending/running/succeeded/failed" json:"state"` // Pod状态：pending/running/succeeded/failed
	Reason        *string        `gorm:"column:reason;comment:原因" json:"reason"`                                                            // 原因
	Message       *string        `gorm:"column:message;comment:消息" json:"message"`                                                          // 消息
	ExitCode      *int32         `gorm:"column:exit_code;comment:退出码" json:"exit_code"`                                                     // 退出码
	Device        *string        `gorm:"column:device;comment:分配的设备（GPU等）" json:"device"`                                                   // 分配的设备（GPU等）
	ResourceUsage *string        `gorm:"column:resource_usage;comment:资源使用情况" json:"resource_usage"`                                        // 资源使用情况
	CreatedAt     *time.Time     `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                  // 创建时间
	ScheduledAt   *time.Time     `gorm:"column:scheduled_at;comment:调度时间" json:"scheduled_at"`                                              // 调度时间
	StartedAt     *time.Time     `gorm:"column:started_at;comment:开始时间" json:"started_at"`                                                  // 开始时间
	FinishedAt    *time.Time     `gorm:"column:finished_at;comment:结束时间" json:"finished_at"`                                                // 结束时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`               // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                                  // 删除时间
	ExtraInfo     *string        `gorm:"column:extra_info;comment:额外信息" json:"extra_info"`                                                  // 额外信息
}

// TableName PodStatusM's table name
func (*PodStatusM) TableName() string {
	return TableNamePodStatusM
}
