// Healthz API 定义，包含健康检查响应的相关消息和状态

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.1
// source: aimtp_server/v1/dag.proto

package aimtp_server_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDAGRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ========== 内部字段（由中间件注入）==========
	// @gotags: json:"-"
	ID int32 `protobuf:"varint,1,opt,name=i_d,json=iD,proto3" json:"-"` // 内部ID
	// @gotags: json:"uid,omitempty" binding:"-"
	UID int64 `protobuf:"varint,2,opt,name=u_i_d,json=uid,proto3" json:"uid,omitempty" binding:"-"` // 用户ID
	// @gotags: json:"uname,omitempty" binding:"-"
	UName string `protobuf:"bytes,3,opt,name=u_name,json=uname,proto3" json:"uname,omitempty" binding:"-"` // 用户名
	// @gotags: json:"ou_name" binding:"-"
	OUName string `protobuf:"bytes,4,opt,name=o_u_name,json=ou_name,proto3" json:"ou_name" binding:"-"` // 组织单元名称
	// @gotags: json:"ou_id" binding:"-"
	OUId       int64  `protobuf:"varint,5,opt,name=o_u_id,json=ou_id,proto3" json:"ou_id" binding:"-"`               // 组织单元ID
	DeviceType string `protobuf:"bytes,6,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // 设备类型
	// ========== 鉴权信息 ==========
	// @gotags: json:"app_id"
	AppId string `protobuf:"bytes,7,opt,name=app_id,proto3" json:"app_id"`
	// @gotags: json:"app_key"
	AppKey string `protobuf:"bytes,8,opt,name=app_key,proto3" json:"app_key"`
	// ========== DAG 基本配置 ==========
	// @gotags: json:"queue_name" binding:"required"
	QueueName string `protobuf:"bytes,9,opt,name=queue_name,proto3" json:"queue_name" binding:"required"` // 队列名称
	// @gotags: json:"dag_name" binding:"required"
	DagName string `protobuf:"bytes,10,opt,name=dag_name,proto3" json:"dag_name" binding:"required"` // DAG 名称
	// @gotags: json:"user_name" binding:"required"
	UserName   string `protobuf:"bytes,11,opt,name=user_name,proto3" json:"user_name" binding:"required"`   // 用户名称
	Department string `protobuf:"bytes,12,opt,name=department,proto3" json:"department,omitempty"` // 部门名称
	// @gotags: json:"type"
	Type string `protobuf:"bytes,13,opt,name=type,proto3" json:"type"` // 类型 batch/stream
	// @gotags: json:"desc"
	Desc string `protobuf:"bytes,14,opt,name=desc,proto3" json:"desc"` // 描述
	// @gotags: json:"priority"
	Priority int32 `protobuf:"varint,15,opt,name=priority,proto3" json:"priority"` // 优先级
	// @gotags: json:"ipd_number"
	IPD_Number string `protobuf:"bytes,16,opt,name=i_p_d_Number,json=ipd_number,proto3" json:"ipd_number"` // IPD编号
	Cron       string `protobuf:"bytes,17,opt,name=cron,proto3" json:"cron,omitempty"`
	// @gotags: json:"engine"
	Engine string `protobuf:"bytes,18,opt,name=engine,proto3" json:"engine"` // 引擎类型 argo/airflow/wolfria/ogra
	// ========== 依赖关系（独立字段）==========
	Dependencies map[string]*DependenciesList `protobuf:"bytes,19,rep,name=dependencies,proto3" json:"dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ========== 时间字段 ==========
	CreateAt *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=createAt,proto3" json:"createAt,omitempty"`
	// ========== 集群配置 ==========
	// @gotags: json:"cluster"
	Cluster string `protobuf:"bytes,21,opt,name=cluster,proto3" json:"cluster"` // 集群名称
	// ========== 通知配置 ==========
	// @gotags: json:"subscribers"
	Subscribers []string `protobuf:"bytes,22,rep,name=subscribers,proto3" json:"subscribers"`
	// ========== 任务定义 ==========
	// @gotags: json:"tasks" binding:"required"
	Tasks []*Task `protobuf:"bytes,23,rep,name=tasks,proto3" json:"tasks" binding:"required"`
	// @gotags: json:"async_tasks"
	AsyncTasks    *AsyncTasks `protobuf:"bytes,24,opt,name=async_tasks,proto3" json:"async_tasks"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDAGRequest) Reset() {
	*x = CreateDAGRequest{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDAGRequest) ProtoMessage() {}

func (x *CreateDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDAGRequest.ProtoReflect.Descriptor instead.
func (*CreateDAGRequest) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDAGRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *CreateDAGRequest) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *CreateDAGRequest) GetUName() string {
	if x != nil {
		return x.UName
	}
	return ""
}

func (x *CreateDAGRequest) GetOUName() string {
	if x != nil {
		return x.OUName
	}
	return ""
}

func (x *CreateDAGRequest) GetOUId() int64 {
	if x != nil {
		return x.OUId
	}
	return 0
}

func (x *CreateDAGRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *CreateDAGRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateDAGRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *CreateDAGRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *CreateDAGRequest) GetDagName() string {
	if x != nil {
		return x.DagName
	}
	return ""
}

func (x *CreateDAGRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateDAGRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateDAGRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateDAGRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateDAGRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateDAGRequest) GetIPD_Number() string {
	if x != nil {
		return x.IPD_Number
	}
	return ""
}

func (x *CreateDAGRequest) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *CreateDAGRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *CreateDAGRequest) GetDependencies() map[string]*DependenciesList {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *CreateDAGRequest) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *CreateDAGRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *CreateDAGRequest) GetSubscribers() []string {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

func (x *CreateDAGRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *CreateDAGRequest) GetAsyncTasks() *AsyncTasks {
	if x != nil {
		return x.AsyncTasks
	}
	return nil
}

type DependenciesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependenciesList) Reset() {
	*x = DependenciesList{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependenciesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependenciesList) ProtoMessage() {}

func (x *DependenciesList) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependenciesList.ProtoReflect.Descriptor instead.
func (*DependenciesList) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{1}
}

func (x *DependenciesList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// 任务定义
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" binding:"required"` // 任务名称
	// @gotags: json:"cluster"
	Cluster string `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster"` // 所属集群名称
	// @gotags: json:"app_id"
	AppId string `protobuf:"bytes,3,opt,name=app_id,proto3" json:"app_id"` // 所属应用ID
	// @gotags: json:"app_key"
	AppKey string `protobuf:"bytes,4,opt,name=app_key,proto3" json:"app_key"` // 所属应用密钥
	// @gotags: json:"queue_name"
	QueueName string `protobuf:"bytes,5,opt,name=queue_name,proto3" json:"queue_name"` // 所属队列名称
	// @gotags: json:"desc"
	Desc string `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc"` // 任务描述
	// @gotags: json:"instance_count"
	InstanceCount int32 `protobuf:"varint,7,opt,name=instance_count,proto3" json:"instance_count"` // 实例数量
	// @gotags: json:"image" binding:"required"
	Image string `protobuf:"bytes,8,opt,name=image,proto3" json:"image" binding:"required"` // 任务镜像
	// @gotags: json:"type"
	Type string `protobuf:"bytes,9,opt,name=type,proto3" json:"type"` // 任务类型 container/job
	// @gotags: json:"schedule_type"
	ScheduleType string `protobuf:"bytes,10,opt,name=schedule_type,proto3" json:"schedule_type"` // 调度类型 topo/default/parallel/interactive/debug
	// @gotags: json:"run_mode"
	RunMode string `protobuf:"bytes,11,opt,name=run_mode,proto3" json:"run_mode"` // 运行模式 foreground/background
	// @gotags: json:"priority"
	Priority int32 `protobuf:"varint,12,opt,name=priority,proto3" json:"priority"` // 任务优先级
	// @gotags: json:"notify"
	Notify bool `protobuf:"varint,13,opt,name=notify,proto3" json:"notify"`
	// @gotags: json:"timeout"
	Timeout int64 `protobuf:"varint,14,opt,name=timeout,proto3" json:"timeout"`
	// @gotags: json:"command" binding:"required"
	Command *Command `protobuf:"bytes,15,opt,name=command,proto3" json:"command" binding:"required"` // 任务命令
	// @gotags: json:"resources" binding:"required"
	Resources *Resource `protobuf:"bytes,16,opt,name=resources,proto3" json:"resources" binding:"required"` // 任务资源
	// @gotags: json:"lifecycle"
	Lifecycle *Lifecycle `protobuf:"bytes,17,opt,name=lifecycle,proto3" json:"lifecycle"` // 任务生命周期
	// @gotags: json:"trigger_rule"
	TriggerRule string `protobuf:"bytes,18,opt,name=trigger_rule,proto3" json:"trigger_rule"` // 触发规则
	// @gotags: json:"retry_strategy"
	RetryStrategy *RetryStrategy `protobuf:"bytes,19,opt,name=retry_strategy,proto3" json:"retry_strategy"` // 重试策略
	// @gotags: json:"env"
	Env map[string]string `protobuf:"bytes,20,rep,name=env,proto3" json:"env" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 环境变量
	// @gotags: json:"subscribers"
	Subscribers []string `protobuf:"bytes,21,rep,name=subscribers,proto3" json:"subscribers"`
	// @gotags: json:"ports"
	Ports         []*ContainerPort `protobuf:"bytes,22,rep,name=ports,proto3" json:"ports"` // 容器端口列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Task) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Task) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *Task) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *Task) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Task) GetInstanceCount() int32 {
	if x != nil {
		return x.InstanceCount
	}
	return 0
}

func (x *Task) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *Task) GetRunMode() string {
	if x != nil {
		return x.RunMode
	}
	return ""
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetNotify() bool {
	if x != nil {
		return x.Notify
	}
	return false
}

func (x *Task) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Task) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Task) GetResources() *Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Task) GetLifecycle() *Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

func (x *Task) GetTriggerRule() string {
	if x != nil {
		return x.TriggerRule
	}
	return ""
}

func (x *Task) GetRetryStrategy() *RetryStrategy {
	if x != nil {
		return x.RetryStrategy
	}
	return nil
}

func (x *Task) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Task) GetSubscribers() []string {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

func (x *Task) GetPorts() []*ContainerPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"command_line" binding:"required"
	CommandLine string `protobuf:"bytes,1,opt,name=command_line,proto3" json:"command_line" binding:"required"` // 实际执行的命令行的命令
	// @gotags: json:"package_path"
	PackagePath string `protobuf:"bytes,2,opt,name=package_path,proto3" json:"package_path"` // 任务包路径
	// @gotags: json:"dir"
	Dir string `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir"` // 解压目录名
	// @gotags: json:"password"
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password"` // 代码包密码
	// @gotags: json:"gits"
	Gits []*GitInfo `protobuf:"bytes,5,rep,name=gits,proto3" json:"gits"` // Git 仓库信息列表
	// @gotags: json:"message_key"
	MessageKey string `protobuf:"bytes,6,opt,name=message_key,proto3" json:"message_key"` // 消息键（parallel任务）
	// @gotags: json:"args"
	Args          *structpb.Struct `protobuf:"bytes,7,opt,name=args,proto3" json:"args"` // 参数 map[string]interface{}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *Command) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

func (x *Command) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Command) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Command) GetGits() []*GitInfo {
	if x != nil {
		return x.Gits
	}
	return nil
}

func (x *Command) GetMessageKey() string {
	if x != nil {
		return x.MessageKey
	}
	return ""
}

func (x *Command) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

type GitInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"repo"
	Repo string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo"`
	// @gotags: json:"branch"
	Branch string `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch"`
	// @gotags: json:"commit_id"
	CommitId string `protobuf:"bytes,3,opt,name=commit_id,proto3" json:"commit_id"`
	// @gotags: json:"tag"
	Tag           string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitInfo) Reset() {
	*x = GitInfo{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitInfo) ProtoMessage() {}

func (x *GitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitInfo.ProtoReflect.Descriptor instead.
func (*GitInfo) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{4}
}

func (x *GitInfo) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GitInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GitInfo) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *GitInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"cpu"
	CPU float32 `protobuf:"fixed32,1,opt,name=c_p_u,json=cpu,proto3" json:"cpu"` // CPU 核心数
	// @gotags: json:"ram"
	RAM int64 `protobuf:"varint,2,opt,name=r_a_m,json=ram,proto3" json:"ram"` // 内存大小（MB）
	// @gotags: json:"gpu"
	GPU float32 `protobuf:"fixed32,3,opt,name=g_p_u,json=gpu,proto3" json:"gpu"` // GPU 核心数
	// @gotags: json:"cpu_mem_ratio"
	CpuMemRatio float32 `protobuf:"fixed32,4,opt,name=cpu_mem_ratio,proto3" json:"cpu_mem_ratio"` // CPU 内存比例
	// @gotags: json:"device_type"
	DeviceType string `protobuf:"bytes,5,opt,name=device_type,proto3" json:"device_type"` // 设备类型
	// @gotags: json:"device_count"
	DeviceCount int32 `protobuf:"varint,6,opt,name=device_count,proto3" json:"device_count"` // 设备数量
	// @gotags: json:"device_num_per_worker"
	DeviceNumPerWorker int32 `protobuf:"varint,7,opt,name=device_num_per_worker,proto3" json:"device_num_per_worker"` // 每个 worker 上的设备数量
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{5}
}

func (x *Resource) GetCPU() float32 {
	if x != nil {
		return x.CPU
	}
	return 0
}

func (x *Resource) GetRAM() int64 {
	if x != nil {
		return x.RAM
	}
	return 0
}

func (x *Resource) GetGPU() float32 {
	if x != nil {
		return x.GPU
	}
	return 0
}

func (x *Resource) GetCpuMemRatio() float32 {
	if x != nil {
		return x.CpuMemRatio
	}
	return 0
}

func (x *Resource) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Resource) GetDeviceCount() int32 {
	if x != nil {
		return x.DeviceCount
	}
	return 0
}

func (x *Resource) GetDeviceNumPerWorker() int32 {
	if x != nil {
		return x.DeviceNumPerWorker
	}
	return 0
}

type Lifecycle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"post_start"
	PostStart *Handler `protobuf:"bytes,1,opt,name=post_start,proto3" json:"post_start"` // 任务启动后钩子
	// @gotags: json:"pre_stop"
	PreStop *Handler `protobuf:"bytes,2,opt,name=pre_stop,proto3" json:"pre_stop"` // 任务停止前钩子
	// @gotags: json:"post_starts"
	PostStarts []*Handler `protobuf:"bytes,3,rep,name=post_starts,proto3" json:"post_starts"` // 任务启动后钩子列表
	// @gotags: json:"pre_stops"
	PreStops      []*Handler `protobuf:"bytes,4,rep,name=pre_stops,proto3" json:"pre_stops"` // 任务停止前钩子列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lifecycle) Reset() {
	*x = Lifecycle{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lifecycle) ProtoMessage() {}

func (x *Lifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lifecycle.ProtoReflect.Descriptor instead.
func (*Lifecycle) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{6}
}

func (x *Lifecycle) GetPostStart() *Handler {
	if x != nil {
		return x.PostStart
	}
	return nil
}

func (x *Lifecycle) GetPreStop() *Handler {
	if x != nil {
		return x.PreStop
	}
	return nil
}

func (x *Lifecycle) GetPostStarts() []*Handler {
	if x != nil {
		return x.PostStarts
	}
	return nil
}

func (x *Lifecycle) GetPreStops() []*Handler {
	if x != nil {
		return x.PreStops
	}
	return nil
}

type Handler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"exec"
	Exec *ExecHandler `protobuf:"bytes,1,opt,name=exec,proto3" json:"exec"` // 执行钩子
	// @gotags: json:"http_get"
	HttpGet *HTTPGetHandler `protobuf:"bytes,2,opt,name=http_get,proto3" json:"http_get"` // HTTP GET 钩子
	// @gotags: json:"redis"
	Redis *RedisHandler `protobuf:"bytes,3,opt,name=redis,proto3" json:"redis"` // Redis 钩子
	// @gotags: json:"upload_message"
	UploadMessage *UploadMessageHandler `protobuf:"bytes,4,opt,name=upload_message,proto3" json:"upload_message"` // 上传消息钩子
	// @gotags: json:"skip_downstream_tasks"
	SkipDownstreamTasks *SkipDownstreamTasksHandler `protobuf:"bytes,5,opt,name=skip_downstream_tasks,proto3" json:"skip_downstream_tasks"` // 跳过下游任务钩子
	// @gotags: json:"check_auto_dp_task_done"
	CheckAutoDpTaskDone *CheckAutoDPTaskDoneHandler `protobuf:"bytes,6,opt,name=check_auto_dp_task_done,proto3" json:"check_auto_dp_task_done"` // 检查 AutoDP 任务完成钩子
	// @gotags: json:"fillback_data_sync"
	FillbackDataSync *FillbackDataSync `protobuf:"bytes,7,opt,name=fillback_data_sync,proto3" json:"fillback_data_sync"` // 数据同步钩子
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Handler) Reset() {
	*x = Handler{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handler) ProtoMessage() {}

func (x *Handler) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handler.ProtoReflect.Descriptor instead.
func (*Handler) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{7}
}

func (x *Handler) GetExec() *ExecHandler {
	if x != nil {
		return x.Exec
	}
	return nil
}

func (x *Handler) GetHttpGet() *HTTPGetHandler {
	if x != nil {
		return x.HttpGet
	}
	return nil
}

func (x *Handler) GetRedis() *RedisHandler {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Handler) GetUploadMessage() *UploadMessageHandler {
	if x != nil {
		return x.UploadMessage
	}
	return nil
}

func (x *Handler) GetSkipDownstreamTasks() *SkipDownstreamTasksHandler {
	if x != nil {
		return x.SkipDownstreamTasks
	}
	return nil
}

func (x *Handler) GetCheckAutoDpTaskDone() *CheckAutoDPTaskDoneHandler {
	if x != nil {
		return x.CheckAutoDpTaskDone
	}
	return nil
}

func (x *Handler) GetFillbackDataSync() *FillbackDataSync {
	if x != nil {
		return x.FillbackDataSync
	}
	return nil
}

type ExecHandler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"command"
	Command       string `protobuf:"bytes,1,opt,name=command,proto3" json:"command"` // 执行命令
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecHandler) Reset() {
	*x = ExecHandler{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecHandler) ProtoMessage() {}

func (x *ExecHandler) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecHandler.ProtoReflect.Descriptor instead.
func (*ExecHandler) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{8}
}

func (x *ExecHandler) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type HTTPGetHandler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"schema"
	Schema string `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema"` // HTTP 协议
	// @gotags: json:"host"
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host"` // HTTP 主机
	// @gotags: json:"port"
	Port int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port"` // HTTP 端口
	// @gotags: json:"path"
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path"` // HTTP 路径
	// @gotags: json:"headers"
	Headers *structpb.Struct `protobuf:"bytes,5,opt,name=headers,proto3" json:"headers"` // HTTP 头
	// @gotags: json:"hook_time_control"
	HookTimeControl *HookTimeControl `protobuf:"bytes,6,opt,name=hook_time_control,proto3" json:"hook_time_control"` // HTTP 钩子时间控制
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HTTPGetHandler) Reset() {
	*x = HTTPGetHandler{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPGetHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPGetHandler) ProtoMessage() {}

func (x *HTTPGetHandler) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPGetHandler.ProtoReflect.Descriptor instead.
func (*HTTPGetHandler) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{9}
}

func (x *HTTPGetHandler) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *HTTPGetHandler) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HTTPGetHandler) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HTTPGetHandler) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPGetHandler) GetHeaders() *structpb.Struct {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPGetHandler) GetHookTimeControl() *HookTimeControl {
	if x != nil {
		return x.HookTimeControl
	}
	return nil
}

// RedisHandler Redis 钩子
type RedisHandler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"key"
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key"` // 键
	// @gotags: json:"addrs"
	Addrs []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs"` // 地址列表
	// @gotags: json:"sentinel_master"
	SentinelMaster string `protobuf:"bytes,3,opt,name=sentinel_master,proto3" json:"sentinel_master"` // 哨兵 Master 名称
	// @gotags: json:"password"
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password"` // 密码
	// @gotags: json:"db"
	Db int32 `protobuf:"varint,5,opt,name=db,proto3" json:"db"` // 数据库索引
	// @gotags: json:"hook_time_control"
	HookTimeControl *HookTimeControl `protobuf:"bytes,6,opt,name=hook_time_control,proto3" json:"hook_time_control"` // Redis 时间控制
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RedisHandler) Reset() {
	*x = RedisHandler{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisHandler) ProtoMessage() {}

func (x *RedisHandler) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisHandler.ProtoReflect.Descriptor instead.
func (*RedisHandler) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{10}
}

func (x *RedisHandler) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RedisHandler) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *RedisHandler) GetSentinelMaster() string {
	if x != nil {
		return x.SentinelMaster
	}
	return ""
}

func (x *RedisHandler) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RedisHandler) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *RedisHandler) GetHookTimeControl() *HookTimeControl {
	if x != nil {
		return x.HookTimeControl
	}
	return nil
}

// UploadMessageHandler 上传消息钩子
type UploadMessageHandler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"path"
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path"` // 路径
	// @gotags: json:"auto_clean"
	AutoClean bool `protobuf:"varint,2,opt,name=auto_clean,proto3" json:"auto_clean"` // 自动清理
	// @gotags: json:"update_max_worker_num"
	UpdateMaxWorkerNum bool `protobuf:"varint,3,opt,name=update_max_worker_num,proto3" json:"update_max_worker_num"` // 更新最大 worker 数量
	// @gotags: json:"msgs"
	Msgs          []string `protobuf:"bytes,4,rep,name=msgs,proto3" json:"msgs"` // 消息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMessageHandler) Reset() {
	*x = UploadMessageHandler{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMessageHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMessageHandler) ProtoMessage() {}

func (x *UploadMessageHandler) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMessageHandler.ProtoReflect.Descriptor instead.
func (*UploadMessageHandler) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{11}
}

func (x *UploadMessageHandler) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadMessageHandler) GetAutoClean() bool {
	if x != nil {
		return x.AutoClean
	}
	return false
}

func (x *UploadMessageHandler) GetUpdateMaxWorkerNum() bool {
	if x != nil {
		return x.UpdateMaxWorkerNum
	}
	return false
}

func (x *UploadMessageHandler) GetMsgs() []string {
	if x != nil {
		return x.Msgs
	}
	return nil
}

// SkipDownstreamTasksHandler 跳过下游任务钩子
type SkipDownstreamTasksHandler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"task_key"
	TaskKey       string `protobuf:"bytes,1,opt,name=task_key,proto3" json:"task_key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipDownstreamTasksHandler) Reset() {
	*x = SkipDownstreamTasksHandler{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipDownstreamTasksHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipDownstreamTasksHandler) ProtoMessage() {}

func (x *SkipDownstreamTasksHandler) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipDownstreamTasksHandler.ProtoReflect.Descriptor instead.
func (*SkipDownstreamTasksHandler) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{12}
}

func (x *SkipDownstreamTasksHandler) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

// CheckAutoDPTaskDoneHandler 检查 AutoDP 任务完成钩子
type CheckAutoDPTaskDoneHandler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"url_key"
	UrlKey        string `protobuf:"bytes,1,opt,name=url_key,proto3" json:"url_key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAutoDPTaskDoneHandler) Reset() {
	*x = CheckAutoDPTaskDoneHandler{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAutoDPTaskDoneHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAutoDPTaskDoneHandler) ProtoMessage() {}

func (x *CheckAutoDPTaskDoneHandler) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAutoDPTaskDoneHandler.ProtoReflect.Descriptor instead.
func (*CheckAutoDPTaskDoneHandler) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{13}
}

func (x *CheckAutoDPTaskDoneHandler) GetUrlKey() string {
	if x != nil {
		return x.UrlKey
	}
	return ""
}

// FillbackDataSync 数据同步钩子
type FillbackDataSync struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"bucket"
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket"` // 存储桶
	// @gotags: json:"command"
	Command       string `protobuf:"bytes,2,opt,name=command,proto3" json:"command"` // 执行命令
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillbackDataSync) Reset() {
	*x = FillbackDataSync{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillbackDataSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillbackDataSync) ProtoMessage() {}

func (x *FillbackDataSync) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillbackDataSync.ProtoReflect.Descriptor instead.
func (*FillbackDataSync) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{14}
}

func (x *FillbackDataSync) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FillbackDataSync) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// HookTimeControl 钩子时间控制
type HookTimeControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"interval"
	Interval *int32 `protobuf:"varint,1,opt,name=interval,proto3,oneof" json:"interval"`
	// @gotags: json:"hook_timeout"
	HookTimeout   int32 `protobuf:"varint,2,opt,name=hook_timeout,proto3" json:"hook_timeout"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookTimeControl) Reset() {
	*x = HookTimeControl{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookTimeControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookTimeControl) ProtoMessage() {}

func (x *HookTimeControl) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookTimeControl.ProtoReflect.Descriptor instead.
func (*HookTimeControl) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{15}
}

func (x *HookTimeControl) GetInterval() int32 {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return 0
}

func (x *HookTimeControl) GetHookTimeout() int32 {
	if x != nil {
		return x.HookTimeout
	}
	return 0
}

// RetryStrategy 重试策略
type RetryStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"limit"
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit"` // 重试次数
	// @gotags: json:"backoff_limit"
	BackoffLimit *int32 `protobuf:"varint,2,opt,name=backoff_limit,proto3,oneof" json:"backoff_limit"` // 重试间隔上限
	// @gotags: json:"ignore_retry_reasons"
	IgnoreRetryReasons []string `protobuf:"bytes,3,rep,name=ignore_retry_reasons,proto3" json:"ignore_retry_reasons"` // 忽略重试原因列表
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RetryStrategy) Reset() {
	*x = RetryStrategy{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryStrategy) ProtoMessage() {}

func (x *RetryStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryStrategy.ProtoReflect.Descriptor instead.
func (*RetryStrategy) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{16}
}

func (x *RetryStrategy) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RetryStrategy) GetBackoffLimit() int32 {
	if x != nil && x.BackoffLimit != nil {
		return *x.BackoffLimit
	}
	return 0
}

func (x *RetryStrategy) GetIgnoreRetryReasons() []string {
	if x != nil {
		return x.IgnoreRetryReasons
	}
	return nil
}

// ContainerPort 容器端口配置
type ContainerPort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"container_port" binding:"required"
	ContainerPort int32 `protobuf:"varint,1,opt,name=container_port,proto3" json:"container_port" binding:"required"` // 容器端口
	// @gotags: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"` // 端口名称
	// @gotags: json:"protocol"
	Protocol      string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol"` // 协议
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerPort) Reset() {
	*x = ContainerPort{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPort) ProtoMessage() {}

func (x *ContainerPort) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerPort.ProtoReflect.Descriptor instead.
func (*ContainerPort) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{17}
}

func (x *ContainerPort) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *ContainerPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// AsyncTasks 异步任务配置
type AsyncTasks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"init_command"
	InitCommand string `protobuf:"bytes,1,opt,name=init_command,proto3" json:"init_command"` // 初始化命令
	// @gotags: json:"global_function_bytes"
	GlobalFunctionBytes string `protobuf:"bytes,2,opt,name=global_function_bytes,proto3" json:"global_function_bytes"`
	// @gotags: json:"tasks"
	Tasks         []*AsyncTask `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks"` // 异步任务列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncTasks) Reset() {
	*x = AsyncTasks{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncTasks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncTasks) ProtoMessage() {}

func (x *AsyncTasks) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncTasks.ProtoReflect.Descriptor instead.
func (*AsyncTasks) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{18}
}

func (x *AsyncTasks) GetInitCommand() string {
	if x != nil {
		return x.InitCommand
	}
	return ""
}

func (x *AsyncTasks) GetGlobalFunctionBytes() string {
	if x != nil {
		return x.GlobalFunctionBytes
	}
	return ""
}

func (x *AsyncTasks) GetTasks() []*AsyncTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// AsyncTask 异步任务
type AsyncTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"name" binding:"required"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" binding:"required"` // 异步任务名称
	// @gotags: json:"args"
	Args *structpb.Struct `protobuf:"bytes,2,opt,name=args,proto3" json:"args"` // 异步任务参数
	// @gotags: json:"function_bytes"
	FunctionBytes string `protobuf:"bytes,3,opt,name=function_bytes,proto3" json:"function_bytes"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncTask) Reset() {
	*x = AsyncTask{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncTask) ProtoMessage() {}

func (x *AsyncTask) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncTask.ProtoReflect.Descriptor instead.
func (*AsyncTask) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{19}
}

func (x *AsyncTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AsyncTask) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AsyncTask) GetFunctionBytes() string {
	if x != nil {
		return x.FunctionBytes
	}
	return ""
}

// CreateDAGResponse 创建 DAG 响应
type CreateDAGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDAGResponse) Reset() {
	*x = CreateDAGResponse{}
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDAGResponse) ProtoMessage() {}

func (x *CreateDAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aimtp_server_v1_dag_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDAGResponse.ProtoReflect.Descriptor instead.
func (*CreateDAGResponse) Descriptor() ([]byte, []int) {
	return file_aimtp_server_v1_dag_proto_rawDescGZIP(), []int{20}
}

var File_aimtp_server_v1_dag_proto protoreflect.FileDescriptor

const file_aimtp_server_v1_dag_proto_rawDesc = "" +
	"\n" +
	"\x19aimtp_server/v1/dag.proto\x12\x0faimtp_server_v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfc\x06\n" +
	"\x10CreateDAGRequest\x12\x0f\n" +
	"\x03i_d\x18\x01 \x01(\x05R\x02iD\x12\x12\n" +
	"\x05u_i_d\x18\x02 \x01(\x03R\x03uid\x12\x15\n" +
	"\x06u_name\x18\x03 \x01(\tR\x05uname\x12\x19\n" +
	"\bo_u_name\x18\x04 \x01(\tR\aou_name\x12\x15\n" +
	"\x06o_u_id\x18\x05 \x01(\x03R\x05ou_id\x12\x1f\n" +
	"\vdevice_type\x18\x06 \x01(\tR\n" +
	"deviceType\x12\x16\n" +
	"\x06app_id\x18\a \x01(\tR\x06app_id\x12\x18\n" +
	"\aapp_key\x18\b \x01(\tR\aapp_key\x12\x1e\n" +
	"\n" +
	"queue_name\x18\t \x01(\tR\n" +
	"queue_name\x12\x1a\n" +
	"\bdag_name\x18\n" +
	" \x01(\tR\bdag_name\x12\x1c\n" +
	"\tuser_name\x18\v \x01(\tR\tuser_name\x12\x1e\n" +
	"\n" +
	"department\x18\f \x01(\tR\n" +
	"department\x12\x12\n" +
	"\x04type\x18\r \x01(\tR\x04type\x12\x12\n" +
	"\x04desc\x18\x0e \x01(\tR\x04desc\x12\x1a\n" +
	"\bpriority\x18\x0f \x01(\x05R\bpriority\x12 \n" +
	"\fi_p_d_Number\x18\x10 \x01(\tR\n" +
	"ipd_number\x12\x12\n" +
	"\x04cron\x18\x11 \x01(\tR\x04cron\x12\x16\n" +
	"\x06engine\x18\x12 \x01(\tR\x06engine\x12W\n" +
	"\fdependencies\x18\x13 \x03(\v23.aimtp_server_v1.CreateDAGRequest.DependenciesEntryR\fdependencies\x126\n" +
	"\bcreateAt\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\x12\x18\n" +
	"\acluster\x18\x15 \x01(\tR\acluster\x12 \n" +
	"\vsubscribers\x18\x16 \x03(\tR\vsubscribers\x12+\n" +
	"\x05tasks\x18\x17 \x03(\v2\x15.aimtp_server_v1.TaskR\x05tasks\x12=\n" +
	"\vasync_tasks\x18\x18 \x01(\v2\x1b.aimtp_server_v1.AsyncTasksR\vasync_tasks\x1ab\n" +
	"\x11DependenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.aimtp_server_v1.DependenciesListR\x05value:\x028\x01\"(\n" +
	"\x10DependenciesList\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"\xd1\x06\n" +
	"\x04Task\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x16\n" +
	"\x06app_id\x18\x03 \x01(\tR\x06app_id\x12\x18\n" +
	"\aapp_key\x18\x04 \x01(\tR\aapp_key\x12\x1e\n" +
	"\n" +
	"queue_name\x18\x05 \x01(\tR\n" +
	"queue_name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12&\n" +
	"\x0einstance_count\x18\a \x01(\x05R\x0einstance_count\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12$\n" +
	"\rschedule_type\x18\n" +
	" \x01(\tR\rschedule_type\x12\x1a\n" +
	"\brun_mode\x18\v \x01(\tR\brun_mode\x12\x1a\n" +
	"\bpriority\x18\f \x01(\x05R\bpriority\x12\x16\n" +
	"\x06notify\x18\r \x01(\bR\x06notify\x12\x18\n" +
	"\atimeout\x18\x0e \x01(\x03R\atimeout\x122\n" +
	"\acommand\x18\x0f \x01(\v2\x18.aimtp_server_v1.CommandR\acommand\x127\n" +
	"\tresources\x18\x10 \x01(\v2\x19.aimtp_server_v1.ResourceR\tresources\x128\n" +
	"\tlifecycle\x18\x11 \x01(\v2\x1a.aimtp_server_v1.LifecycleR\tlifecycle\x12\"\n" +
	"\ftrigger_rule\x18\x12 \x01(\tR\ftrigger_rule\x12F\n" +
	"\x0eretry_strategy\x18\x13 \x01(\v2\x1e.aimtp_server_v1.RetryStrategyR\x0eretry_strategy\x120\n" +
	"\x03env\x18\x14 \x03(\v2\x1e.aimtp_server_v1.Task.EnvEntryR\x03env\x12 \n" +
	"\vsubscribers\x18\x15 \x03(\tR\vsubscribers\x124\n" +
	"\x05ports\x18\x16 \x03(\v2\x1e.aimtp_server_v1.ContainerPortR\x05ports\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\aCommand\x12\"\n" +
	"\fcommand_line\x18\x01 \x01(\tR\fcommand_line\x12\"\n" +
	"\fpackage_path\x18\x02 \x01(\tR\fpackage_path\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12,\n" +
	"\x04gits\x18\x05 \x03(\v2\x18.aimtp_server_v1.GitInfoR\x04gits\x12 \n" +
	"\vmessage_key\x18\x06 \x01(\tR\vmessage_key\x12+\n" +
	"\x04args\x18\a \x01(\v2\x17.google.protobuf.StructR\x04args\"e\n" +
	"\aGitInfo\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1c\n" +
	"\tcommit_id\x18\x03 \x01(\tR\tcommit_id\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\"\xe8\x01\n" +
	"\bResource\x12\x12\n" +
	"\x05c_p_u\x18\x01 \x01(\x02R\x03cpu\x12\x12\n" +
	"\x05r_a_m\x18\x02 \x01(\x03R\x03ram\x12\x12\n" +
	"\x05g_p_u\x18\x03 \x01(\x02R\x03gpu\x12$\n" +
	"\rcpu_mem_ratio\x18\x04 \x01(\x02R\rcpu_mem_ratio\x12 \n" +
	"\vdevice_type\x18\x05 \x01(\tR\vdevice_type\x12\"\n" +
	"\fdevice_count\x18\x06 \x01(\x05R\fdevice_count\x124\n" +
	"\x15device_num_per_worker\x18\a \x01(\x05R\x15device_num_per_worker\"\xef\x01\n" +
	"\tLifecycle\x128\n" +
	"\n" +
	"post_start\x18\x01 \x01(\v2\x18.aimtp_server_v1.HandlerR\n" +
	"post_start\x124\n" +
	"\bpre_stop\x18\x02 \x01(\v2\x18.aimtp_server_v1.HandlerR\bpre_stop\x12:\n" +
	"\vpost_starts\x18\x03 \x03(\v2\x18.aimtp_server_v1.HandlerR\vpost_starts\x126\n" +
	"\tpre_stops\x18\x04 \x03(\v2\x18.aimtp_server_v1.HandlerR\tpre_stops\"\x99\x04\n" +
	"\aHandler\x120\n" +
	"\x04exec\x18\x01 \x01(\v2\x1c.aimtp_server_v1.ExecHandlerR\x04exec\x12;\n" +
	"\bhttp_get\x18\x02 \x01(\v2\x1f.aimtp_server_v1.HTTPGetHandlerR\bhttp_get\x123\n" +
	"\x05redis\x18\x03 \x01(\v2\x1d.aimtp_server_v1.RedisHandlerR\x05redis\x12M\n" +
	"\x0eupload_message\x18\x04 \x01(\v2%.aimtp_server_v1.UploadMessageHandlerR\x0eupload_message\x12a\n" +
	"\x15skip_downstream_tasks\x18\x05 \x01(\v2+.aimtp_server_v1.SkipDownstreamTasksHandlerR\x15skip_downstream_tasks\x12e\n" +
	"\x17check_auto_dp_task_done\x18\x06 \x01(\v2+.aimtp_server_v1.CheckAutoDPTaskDoneHandlerR\x17check_auto_dp_task_done\x12Q\n" +
	"\x12fillback_data_sync\x18\a \x01(\v2!.aimtp_server_v1.FillbackDataSyncR\x12fillback_data_sync\"'\n" +
	"\vExecHandler\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"\xe7\x01\n" +
	"\x0eHTTPGetHandler\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x121\n" +
	"\aheaders\x18\x05 \x01(\v2\x17.google.protobuf.StructR\aheaders\x12N\n" +
	"\x11hook_time_control\x18\x06 \x01(\v2 .aimtp_server_v1.HookTimeControlR\x11hook_time_control\"\xdc\x01\n" +
	"\fRedisHandler\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\x12(\n" +
	"\x0fsentinel_master\x18\x03 \x01(\tR\x0fsentinel_master\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x05 \x01(\x05R\x02db\x12N\n" +
	"\x11hook_time_control\x18\x06 \x01(\v2 .aimtp_server_v1.HookTimeControlR\x11hook_time_control\"\x94\x01\n" +
	"\x14UploadMessageHandler\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"auto_clean\x18\x02 \x01(\bR\n" +
	"auto_clean\x124\n" +
	"\x15update_max_worker_num\x18\x03 \x01(\bR\x15update_max_worker_num\x12\x12\n" +
	"\x04msgs\x18\x04 \x03(\tR\x04msgs\"8\n" +
	"\x1aSkipDownstreamTasksHandler\x12\x1a\n" +
	"\btask_key\x18\x01 \x01(\tR\btask_key\"6\n" +
	"\x1aCheckAutoDPTaskDoneHandler\x12\x18\n" +
	"\aurl_key\x18\x01 \x01(\tR\aurl_key\"D\n" +
	"\x10FillbackDataSync\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"c\n" +
	"\x0fHookTimeControl\x12\x1f\n" +
	"\binterval\x18\x01 \x01(\x05H\x00R\binterval\x88\x01\x01\x12\"\n" +
	"\fhook_timeout\x18\x02 \x01(\x05R\fhook_timeoutB\v\n" +
	"\t_interval\"\x96\x01\n" +
	"\rRetryStrategy\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12)\n" +
	"\rbackoff_limit\x18\x02 \x01(\x05H\x00R\rbackoff_limit\x88\x01\x01\x122\n" +
	"\x14ignore_retry_reasons\x18\x03 \x03(\tR\x14ignore_retry_reasonsB\x10\n" +
	"\x0e_backoff_limit\"g\n" +
	"\rContainerPort\x12&\n" +
	"\x0econtainer_port\x18\x01 \x01(\x05R\x0econtainer_port\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\x98\x01\n" +
	"\n" +
	"AsyncTasks\x12\"\n" +
	"\finit_command\x18\x01 \x01(\tR\finit_command\x124\n" +
	"\x15global_function_bytes\x18\x02 \x01(\tR\x15global_function_bytes\x120\n" +
	"\x05tasks\x18\x03 \x03(\v2\x1a.aimtp_server_v1.AsyncTaskR\x05tasks\"t\n" +
	"\tAsyncTask\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04args\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04args\x12&\n" +
	"\x0efunction_bytes\x18\x03 \x01(\tR\x0efunction_bytes\"\x13\n" +
	"\x11CreateDAGResponseB/Z-aimtp/pkg/api/aimtp_server/v1;aimtp_server_v1b\x06proto3"

var (
	file_aimtp_server_v1_dag_proto_rawDescOnce sync.Once
	file_aimtp_server_v1_dag_proto_rawDescData []byte
)

func file_aimtp_server_v1_dag_proto_rawDescGZIP() []byte {
	file_aimtp_server_v1_dag_proto_rawDescOnce.Do(func() {
		file_aimtp_server_v1_dag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aimtp_server_v1_dag_proto_rawDesc), len(file_aimtp_server_v1_dag_proto_rawDesc)))
	})
	return file_aimtp_server_v1_dag_proto_rawDescData
}

var file_aimtp_server_v1_dag_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_aimtp_server_v1_dag_proto_goTypes = []any{
	(*CreateDAGRequest)(nil),           // 0: aimtp_server_v1.CreateDAGRequest
	(*DependenciesList)(nil),           // 1: aimtp_server_v1.DependenciesList
	(*Task)(nil),                       // 2: aimtp_server_v1.Task
	(*Command)(nil),                    // 3: aimtp_server_v1.Command
	(*GitInfo)(nil),                    // 4: aimtp_server_v1.GitInfo
	(*Resource)(nil),                   // 5: aimtp_server_v1.Resource
	(*Lifecycle)(nil),                  // 6: aimtp_server_v1.Lifecycle
	(*Handler)(nil),                    // 7: aimtp_server_v1.Handler
	(*ExecHandler)(nil),                // 8: aimtp_server_v1.ExecHandler
	(*HTTPGetHandler)(nil),             // 9: aimtp_server_v1.HTTPGetHandler
	(*RedisHandler)(nil),               // 10: aimtp_server_v1.RedisHandler
	(*UploadMessageHandler)(nil),       // 11: aimtp_server_v1.UploadMessageHandler
	(*SkipDownstreamTasksHandler)(nil), // 12: aimtp_server_v1.SkipDownstreamTasksHandler
	(*CheckAutoDPTaskDoneHandler)(nil), // 13: aimtp_server_v1.CheckAutoDPTaskDoneHandler
	(*FillbackDataSync)(nil),           // 14: aimtp_server_v1.FillbackDataSync
	(*HookTimeControl)(nil),            // 15: aimtp_server_v1.HookTimeControl
	(*RetryStrategy)(nil),              // 16: aimtp_server_v1.RetryStrategy
	(*ContainerPort)(nil),              // 17: aimtp_server_v1.ContainerPort
	(*AsyncTasks)(nil),                 // 18: aimtp_server_v1.AsyncTasks
	(*AsyncTask)(nil),                  // 19: aimtp_server_v1.AsyncTask
	(*CreateDAGResponse)(nil),          // 20: aimtp_server_v1.CreateDAGResponse
	nil,                                // 21: aimtp_server_v1.CreateDAGRequest.DependenciesEntry
	nil,                                // 22: aimtp_server_v1.Task.EnvEntry
	(*timestamppb.Timestamp)(nil),      // 23: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 24: google.protobuf.Struct
}
var file_aimtp_server_v1_dag_proto_depIdxs = []int32{
	21, // 0: aimtp_server_v1.CreateDAGRequest.dependencies:type_name -> aimtp_server_v1.CreateDAGRequest.DependenciesEntry
	23, // 1: aimtp_server_v1.CreateDAGRequest.createAt:type_name -> google.protobuf.Timestamp
	2,  // 2: aimtp_server_v1.CreateDAGRequest.tasks:type_name -> aimtp_server_v1.Task
	18, // 3: aimtp_server_v1.CreateDAGRequest.async_tasks:type_name -> aimtp_server_v1.AsyncTasks
	3,  // 4: aimtp_server_v1.Task.command:type_name -> aimtp_server_v1.Command
	5,  // 5: aimtp_server_v1.Task.resources:type_name -> aimtp_server_v1.Resource
	6,  // 6: aimtp_server_v1.Task.lifecycle:type_name -> aimtp_server_v1.Lifecycle
	16, // 7: aimtp_server_v1.Task.retry_strategy:type_name -> aimtp_server_v1.RetryStrategy
	22, // 8: aimtp_server_v1.Task.env:type_name -> aimtp_server_v1.Task.EnvEntry
	17, // 9: aimtp_server_v1.Task.ports:type_name -> aimtp_server_v1.ContainerPort
	4,  // 10: aimtp_server_v1.Command.gits:type_name -> aimtp_server_v1.GitInfo
	24, // 11: aimtp_server_v1.Command.args:type_name -> google.protobuf.Struct
	7,  // 12: aimtp_server_v1.Lifecycle.post_start:type_name -> aimtp_server_v1.Handler
	7,  // 13: aimtp_server_v1.Lifecycle.pre_stop:type_name -> aimtp_server_v1.Handler
	7,  // 14: aimtp_server_v1.Lifecycle.post_starts:type_name -> aimtp_server_v1.Handler
	7,  // 15: aimtp_server_v1.Lifecycle.pre_stops:type_name -> aimtp_server_v1.Handler
	8,  // 16: aimtp_server_v1.Handler.exec:type_name -> aimtp_server_v1.ExecHandler
	9,  // 17: aimtp_server_v1.Handler.http_get:type_name -> aimtp_server_v1.HTTPGetHandler
	10, // 18: aimtp_server_v1.Handler.redis:type_name -> aimtp_server_v1.RedisHandler
	11, // 19: aimtp_server_v1.Handler.upload_message:type_name -> aimtp_server_v1.UploadMessageHandler
	12, // 20: aimtp_server_v1.Handler.skip_downstream_tasks:type_name -> aimtp_server_v1.SkipDownstreamTasksHandler
	13, // 21: aimtp_server_v1.Handler.check_auto_dp_task_done:type_name -> aimtp_server_v1.CheckAutoDPTaskDoneHandler
	14, // 22: aimtp_server_v1.Handler.fillback_data_sync:type_name -> aimtp_server_v1.FillbackDataSync
	24, // 23: aimtp_server_v1.HTTPGetHandler.headers:type_name -> google.protobuf.Struct
	15, // 24: aimtp_server_v1.HTTPGetHandler.hook_time_control:type_name -> aimtp_server_v1.HookTimeControl
	15, // 25: aimtp_server_v1.RedisHandler.hook_time_control:type_name -> aimtp_server_v1.HookTimeControl
	19, // 26: aimtp_server_v1.AsyncTasks.tasks:type_name -> aimtp_server_v1.AsyncTask
	24, // 27: aimtp_server_v1.AsyncTask.args:type_name -> google.protobuf.Struct
	1,  // 28: aimtp_server_v1.CreateDAGRequest.DependenciesEntry.value:type_name -> aimtp_server_v1.DependenciesList
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_aimtp_server_v1_dag_proto_init() }
func file_aimtp_server_v1_dag_proto_init() {
	if File_aimtp_server_v1_dag_proto != nil {
		return
	}
	file_aimtp_server_v1_dag_proto_msgTypes[15].OneofWrappers = []any{}
	file_aimtp_server_v1_dag_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aimtp_server_v1_dag_proto_rawDesc), len(file_aimtp_server_v1_dag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aimtp_server_v1_dag_proto_goTypes,
		DependencyIndexes: file_aimtp_server_v1_dag_proto_depIdxs,
		MessageInfos:      file_aimtp_server_v1_dag_proto_msgTypes,
	}.Build()
	File_aimtp_server_v1_dag_proto = out.File
	file_aimtp_server_v1_dag_proto_goTypes = nil
	file_aimtp_server_v1_dag_proto_depIdxs = nil
}
