// Healthz API 定义，包含健康检查响应的相关消息和状态

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package aimtp_server_v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *CreateDAGRequest) Default() {
}

func (x *DependenciesList) Default() {
}

func (x *Task) Default() {
}

func (x *Command) Default() {
}

func (x *GitInfo) Default() {
}

func (x *Resource) Default() {
}

func (x *Lifecycle) Default() {
}

func (x *Handler) Default() {
}

func (x *ExecHandler) Default() {
}

func (x *HTTPGetHandler) Default() {
}

func (x *RedisHandler) Default() {
}

func (x *UploadMessageHandler) Default() {
}

func (x *SkipDownstreamTasksHandler) Default() {
}

func (x *CheckAutoDPTaskDoneHandler) Default() {
}

func (x *FillbackDataSync) Default() {
}

func (x *HookTimeControl) Default() {
}

func (x *RetryStrategy) Default() {
}

func (x *ContainerPort) Default() {
}

func (x *AsyncTasks) Default() {
}

func (x *AsyncTask) Default() {
}

func (x *CreateDAGResponse) Default() {
}
